### ISSUE TITLE
.vjs-share is applied to the entire player

### ISSUE THREAD

**Issue by Discookie** [mkhazov/videojs-share#12]
Discussed further in omarroth/invidious#160.

Fanboy's Social Blocking and Fanboy's Annoyance List block the class `.vjs-share`.

This class is applied to the entire video frame here, along with `.vjs-videojs-share`:
https://github.com/mkhazov/videojs-share/blob/fb04cff70a5f0e73450aa9560a49a64432616af2/src/plugin.js#L37-L42
But later you only make use of `.vjs-videojs-share` on the frame, while using `.vjs-share` for the button.

And thus the entire player is blocked, instead of only the share button.

**Comment by avdeev** [comment]
@Discookie @AlertDOTEXE PR welcome :)

**Comment by omarroth** [comment]
Appears to be fixed using the latest version of [Fanboy's Social Blocking](https://easylist.to/easylist/fanboy-social.txt) and [Fanboy's Annoyance List](https://easylist.to/easylist/fanboy-annoyance.txt). Both now contain this line:
```css
/videojs-share.
```

Which blocks assets for this plugin, so the player still works as normal. I believe this can be closed.
