### ISSUE TITLE
share buttons not working

### ISSUE THREAD

**Issue by tunmsk** [mkhazov/videojs-share#2]
hello 
thank you for your great work and sharing it 
I installed your plugin on my website copying link and embed code work perfectly but not social buttons : I tried them all
here's an url to check https://videos.arabeevideo.com/watch/p127-royal-enfield-cont
is it possible to add custom embed code ?

**Comment by mkhazov** [comment]
You can pass custom embed code as `embedCode` property in the plugin options object.

**Comment by kenanbalija** [comment]
Would you be kind and provide an example of share button implementation (fb or smth)? 😸

**Comment by mkhazov** [comment]
Take a look at https://neuron-digital.github.io/wjplayer/examples/mp4.html

**Comment by tunmsk** [comment]
I'm not very comfortable with js programming neither with videojs , but seems like this is a customized player with many advanced featured
I took a look into the source code , seems you packed plugins together , is it possible to add other plugins like playlist or context menu to your player?

**Comment by kenanbalija** [comment]
@tunmsk videojs has that already. He improved it with his own plugin. 
Check on https://github.com/videojs/video.js
