### ISSUE TITLE
share icon display after full screen

### ISSUE THREAD

**Issue by mannanzinat** [mkhazov/videojs-share#5]
**can you please tell me how can i put share icon before fullscreen icon??**

**Comment by avdeev** [comment]
We down support this feature now. But you can make PR. :)

Need change this line
https://github.com/mkhazov/videojs-share/blob/master/src/plugin.js#L29
for pass new `indexopt` (http://docs.videojs.com/controlbar#addChild) argument.

**Comment by mannanzinat** [comment]
Can you please send alternative code

**Comment by avdeev** [comment]
@mannanzinat Try something like this

```
const index = player.getChild('controlBar').children_.length - 1;
player.getChild('controlBar').addChild('ShareButton', options, index);
```

**Comment by avdeev** [comment]
Closed due inactivity
