### ISSUE TITLE
Facebook share button

### ISSUE THREAD

**Issue by mstorne** [mkhazov/videojs-share#9]
Hi, I am trying to implement share plugin into my player, but I have a problem with facebook. All the buttons show up, except Facebook. I added fbAppId and nothing happens.

Thank you,
Marko.

**Comment by mstorne** [comment]
In my js file it's already fbFeed and it still doesn't work.

**Comment by avdeev** [comment]
@mstorne Try this solution
https://github.com/mkhazov/videojs-share/pull/8/files

**Comment by avdeev** [comment]
@mstorne Is there any news?
If still valid, you can reopen this issue.

I created v3.0.0 with #8 PR.
